baseurl = "/"
languageCode = "en-us"
title = "Seely Street Bed and Breakfast"
#footnotereturnlinkcontents = "↩"

#sectionPagesMenu = "main"

[[menu.main]]
    name = "Welcome"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Contact"
    url = "/Contact/"
    weight = 5
[[menu.main]]
    name = "Rooms"
    url = "/rooms/"
    weight = 2

[params]
    description = "Seely Street Bed and Breakfast"
    footer = "&copy; [Seely Street Bed & Breakfast](https://seelystreet.github.io) 2019 -- 2020"

