baseurl = "/"
languageCode = "en-us"
title = "Seely Street Bed and Breakfast"

#sectionPagesMenu = "main"

[[menu.main]]
    name = "Welcome"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Rooms"
    url = "/rooms/"
    weight = 2
[[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 3
[[menu.main]]
    name = "Facilities"
    url = "/facilities/"
    weight = 4
[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 5
[[menu.main]]
    name = "T&C's"
    url = "/hello/"
    weight = 6

[params]
    description = "Seely Street Bed and Breakfast"
    footer = "&copy; [Seely Street Bed & Breakfast](https://seelystreet.github.io) 2020"

